# -*- coding: utf-8 -*-
"""assignment 1 linqian shen.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ICetFHLY4H7tI4DgZruRZD2SopkylKZe
"""

import pandas as pd
import re

df_list = []
with open('/content/people_1.txt') as f:
    for line in f:
        # remove whitespace at the start and the newline at the end
        line = line.strip()
        # split each column on whitespace
        columns = re.split('\s+', line, maxsplit=4)
        df_list.append(columns)

df = pd.DataFrame(df_list)
print(df.head())

new_header = df.iloc[0]
df = df[1:] 
df.columns = new_header 
print(df.head())

df['FirstName'] = df['FirstName'].str.upper()

df['LastName'] = df['LastName'].str.upper()

df['Phone'] = df['Phone'].str.replace('-', '')

print(df.head())

print(df.info)

result_df = df.drop_duplicates(subset=['FirstName', 'LastName','Phone'], keep='first')

print(result_df.info)

df_list2 = []
with open('/content/people_2.txt') as f2:
    for line in f2:
        # remove whitespace at the start and the newline at the end
        line = line.strip()
        # split each column on whitespace
        columns = re.split('\s+', line, maxsplit=4)
        df_list2.append(columns)

df2 = pd.DataFrame(df_list2)
print(df2.head())

new_header2 = df2.iloc[0]
df2 = df2[1:] 
df2.columns = new_header 
print(df2.head())

df2['FirstName'] = df2['FirstName'].str.upper()

df2['LastName'] = df2['LastName'].str.upper()

df2['Phone'] = df2['Phone'].str.replace('-', '')

print(df.head())
print(df.info)

result_df2 = df2.drop_duplicates(subset=['FirstName', 'LastName','Phone'], keep='first')
print(result_df.info)