# -*- coding: utf-8 -*-
"""movie assignment 2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hhW6ytP2gYBcWALBs6GO9Xusnk3Bh8K4
"""

import pandas as pd
import json

with open('/content/movie (1).json') as json_file:
    data = json.load(json_file)

data1 = data['movie'][:1000]
data2 = data['movie'][1000:2000]
data3 = data['movie'][2000:3000]
data4 = data['movie'][3000:4000]
data5 = data['movie'][4000:5000]
data6 = data['movie'][5000:6000]
data7 = data['movie'][6000:7000]
data8 = data['movie'][7000:8000]
data9 = data['movie'][8000:9000]
data10 = data['movie'][9000:10000]

data_dict1 = {'movie': [data1]}
data_dict2 = {'movie': [data2]}
data_dict3 = {'movie': [data3]}
data_dict4 = {'movie': [data4]}
data_dict5 = {'movie': [data5]}
data_dict6 = {'movie': [data6]}
data_dict7 = {'movie': [data8]}
data_dict8 = {'movie': [data8]}
data_dict9 = {'movie': [data9]}
data_dict10 = {'movie': [data10]}

data_json1 = json.dumps(data_dict1)
data_json2 = json.dumps(data_dict2)
data_json3 = json.dumps(data_dict3)
data_json4 = json.dumps(data_dict4)
data_json5 = json.dumps(data_dict5)
data_json6 = json.dumps(data_dict6)
data_json7 = json.dumps(data_dict7)
data_json8 = json.dumps(data_dict8)
data_json9 = json.dumps(data_dict9)
data_json10 = json.dumps(data_dict10)